#!/bin/bash

# Author: Bernardo Gomez

config="/usr/local/cgi-bin/" 
. ${config}webserver_environ     # dot in environ variables

# export all of the environ variables to my children
for env_var in $(cat ${config}webserver_environ | awk -F'=' '{print $1}')
do
  export ${env_var}
done


/sirsi/webserver/bin/webserverAccess /sirsi/webserver/bin/process_primo_request.py /sirsi/webserver/config/document_delivery_primo.cfg
